name: ci

on:
  push:
    branches: main

jobs:
  slim:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          file: test/Dockerfile
          push: false
          tags: ${{ env.IMAGE }}:${{ env.TAG }}
          context: test/

      - name: Before
        run: docker image ls "${{ env.IMAGE }}"

      - name: docker-slim
        uses: kitabisa/docker-slim-action@master
        id: slim
        env:
          DSLIM_HTTP_PROBE: false
        with:
          target: ${{ env.IMAGE }}:${{ env.TAG }}
          overwrite: ${{ matrix.overwrite }}

      - name: After
        run: docker image ls "${{ env.IMAGE }}"

      - name: Report
        env:
          REPORT: ${{ steps.slim.outputs.report }} # report is JSON format
        run: echo "${REPORT}"
        env:
          DSLIM_LOG_LEVEL: debug
          DSLIM_HTTP_PROBE: false
        with:
          target: ${{ github.repository }}:latest
          tag: "slim"

      - name: Push Slimmed Docker Image
        run: docker image push "${{ github.repository }}:slim"
